export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_UPDATE_PRODUCT = 'GET_UPDATE_PRODUCT';
export const RESET_ITEM_EDITING = 'RESET_ITEM_EDITING';